title:             yeyewon Blog
email:             yeyewon.j@gmail.com
description:       
author:            yeyewon
baseurl:          
url:               "https://yeyewon.github.io/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
