title:             yewon Portfolio
email:             yeyewon.j@gmail.com
description:       Let me introduce
author:            yeyewon
baseurl:          
url:               "https://yeyewon.github.io/"

# Social Profiles
twitter_username:  SBootstrap
github_username:   yeyewon
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
# ...
  collections:
  tags:
    output: true
    permalink: /tags/:path/
# ...
defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag
# ...
